### ISSUE TITLE
auth-git2 0.5.8 does not compile with git2 0.21.0

### ISSUE THREAD

**Issue by onilonil** [de-vri-es/auth-git2-rs#12]
Hi,

I encountered a compilation error when using auth-git2 0.5.8.

Environment
OS: Windows 11
Rust edition: 2024
auth-git2: 0.5.8
git2: 0.21.0
Reproduction

A minimal project with:

[dependencies]
auth-git2 = "0.5.8"

Running:

cargo check

results in:

error[E0599]: no associated function or constant named `credential_helper` found for struct `Cred` in the current scope

--> auth-git2-0.5.8/src/lib.rs:575:23

match git2::Cred::credential_helper(git_config, url, username) {
                   ^^^^^^^^^^^^^^^^^ associated function or constant not found in `Cred`

The error comes from this code in auth-git2:

match git2::Cred::credential_helper(git_config, url, username) {
    Ok(x) => return Ok(x),
    Err(e) => debug!("credentials_callback: failed to use credential helper: {e}"),
}

I found that using git2 0.20.4 instead allows auth-git2 0.5.8 to compile successfully.

I also noticed that auth-git2 0.6.0 now explicitly depends on git2 >=0.21, <0.22, while the credential_helper call is still present in the source code.

I am not sure whether this is expected or whether git2 0.21 compatibility still needs to be addressed, so I wanted to report it.

Thank you for maintaining this crate!

**Comment by onilonil** [comment]
Update:

I tested auth-git2 0.5.8 again and confirmed that it does not compile with git2 0.21.0.

I also tested auth-git2 0.6.0 with git2 0.21.0, and it compiles successfully.

So it looks like the issue is specific to auth-git2 0.5.8 and has already been fixed in 0.6.0.

Thanks!

**Comment by de-vri-es** [comment]
Yeah, indeed, you need `auth-git2-v0.6.0` for `git2-v0.21`.

I do wonder how you managed to even get `auth-git2-v0.5.8` to build with `git2-v0.21`, since the version requirement of `auth-git2-v0.5.8` specifies `git2 <v0.21` :o

**Comment by onilonil** [comment]
Yeah, you're right. I encountered the compilation error while installing dioxus-cli, and I initially thought that git2-v0.21 was being pulled in by auth-git2-v0.5.8.

After looking into it more carefully, I realized that my original report was mistaken.

Sorry for the confusion, and thanks for pointing this out!

**Comment by de-vri-es** [comment]
Hmm, that still leaves me wondering how you got that particular error. You should not be getting compilation errors in a dependency, unless someone somewhere made a mistake in version requirements. And it could very well be `auth-git2`.

**Comment by onilonil** [comment]
I removed `Cargo.lock` and let Cargo resolve everything from scratch.

The result is still:

```text
auth-git2 v0.5.8
├── dirs v6.0.0
├── git2 v0.21.0
└── terminal-prompt v0.2.3
```

So this is reproducible in a minimal project with only:

```toml
[dependencies]
auth-git2 = "0.5.8"
```

There are no other direct dependencies and no existing `Cargo.lock` involved.

The published `auth-git2 0.5.8` manifest specifies:

```toml
git2 = { version = ">0.14, <21.0", default-features = false }
```

but Cargo is still resolving `git2 0.21.0`.

So I'm also not sure why Cargo considers `0.21.0` valid here.

**Comment by onilonil** [comment]
dioxus-cli depends on auth-git2 v0.5.8, which specifies git2 <21.0 in its Cargo.toml. This constraint is too broad, so Cargo resolves it to git2 v0.21.0. However, auth-git2 v0.5.8 is not compatible with git2 v0.21.0, causing the compilation to fail.

**Comment by de-vri-es** [comment]
Oh... I didn't write `<0.21`, I wrote `<21.0`.

Oopsie..

I will do a patch release 0.5.9 to fix that.

**Comment by onilonil** [comment]
Ahh, that explains everything! 

Thanks for confirming and for fixing it in 0.5.9. Glad we got to the bottom of it!

**Comment by de-vri-es** [comment]
Right.. this typo has been in there since `v0.3.3` 😬 

I'll leave 0.3 and 0.4 as they are, but I will yank all 0.5.x that have this problem.

Thanks for reporting it! Not a false alarm!

**Comment by onilonil** [comment]
Haha, glad to hear it! 😄

Thanks for taking the time to investigate it. I’m happy it turned out to be a real issue and not just something on my end.

Looking forward to 0.5.9!

**Comment by de-vri-es** [comment]
v0.5.9 is released! 🚀

I'll close the issue now. Thanks again for reporting it!
